config/routes.rb
Rails.application.routes.draw do

  root 'integrations#index'

  resources :integrations, :constraints => { :id => /.*/ } do
    member do
      get 'subscriptions'
      get 'relations'
      get 'backends'
      get 'contacts'
    end
  end

  resources :clients, :constraints => { :id => /.*/ } do
    member do
      get 'subscriptions'
      get 'contacts'
    end
  end

  resources :backends, :constraints => { :id => /.*/ } do
    member do
      get 'integrations'
      get 'contacts'
    end
  end

  resources :systems, :constraints => { :id => /.*/ } do
    member do
      get 'provides'
      get 'contacts'
    end
  end

  resources :contacts, :constraints => { :id => /.*/ } do
    member do
      get 'roles'
    end
  end

end

app/models/backend.rb
class Backend 
  include ActiveModel::Model
  attr_accessor :identifier, :name, :group, :system,:system_id
  attr_accessor :properties
  attr_accessor :description,:tags

  def self.all
    Registry.backends
  end

  def self.find_by_id(id)
    all.find {|s| s.id==id}
  end

  def self.find_all_by_system_id(system_id)
    all.find_all {|s| s.system_id==system_id}
  end

  def initialize(identifier)
    @properties=[]
    self.identifier=identifier
  end

  def integrations
   IntegrationBackend.find_all_by_backend_id(self.id).map{|s| s.integration}
  end

  def integration_count
    integrations.count
  end

  def system
    System.find_by_id(system_id)
  end

  def group
    @group || (system && system.group)
  end

  def contact_roles
    Role.find_all_by_backend_id(self.id)
  end

  def to_s
    name
  end

  def name
    @name || (system && system.name) || identifier
  end

  def id
    self.identifier.gsub(/[^\w]/,"_") 
  end

  def persisted?
    true
  end
end

app/controllers/backends_controller.rb
class BackendsController < ApplicationController
  # GET /backends
  # GET /backends.json
  def index
    params[:order] ||= 'name'
    keys=["name","group","identifier","integration_count"]
    @backends = filter_and_sort(Backend.all,keys,params)

    respond_to do |format|
      format.html # index.html.erb
      format.csv # index.csv.rb
      format.json { render json: @backends }
    end
  end

  # GET /backends/1
  # GET /backends/1.json
  def show
    @backend = Backend.find_by_id(params[:id])

    respond_to do |format|
      format.html { redirect_to integrations_backend_url(@backend) }
      format.json { render json: @backend }
    end
  end

  # GET /backends/1/integrations
  # GET /backends/1/integrations.json
  def integrations
    params[:order] ||= 'name'
    keys=["name","group"]
    @backend = Backend.find_by_id(params[:id])
    @integrations = filter_and_sort(@backend.integrations,keys,params)

    respond_to do |format|
      format.html
      format.csv # backends.csv.rb
      format.json { render json: @integrations }
    end
  end

  # GET /backends/1/contacts
  # GET /backends/1/contacts.json
  def contacts
    params[:order]||='contact'
    keys=["contact","name","email"]
    @backend = Backend.find_by_id(params[:id])
    @roles = filter_and_sort(@backend.contact_roles,keys,params)

    respond_to do |format|
      format.html 
      format.csv  {render :template => "shared/contacts.csv.rb"}
      format.json { render json: @roles }
    end
  end

end

app/views/backends/_backend.html.erb
<% backend||=@backend %>
<% record||=backend %>
<% hide_toolbar||=false %>

<%= div_for(backend,:class => 'show') do %>
<table class="show" width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <th><%= "Name" %>:</th>
		<td><%= backend.name %></td>
	  <th><%= "Id" %>:</th>
		<td><%= backend.identifier %></td>
	</tr>
	<tr>
	  <th><%= "System" %>:</th>
    <td><%= backend.system && link_to(backend.system,system_path(backend.system))%></td>
	  <th><%= "Group" %>:</th>
    <td><%= backend.group %></td>
	</tr>

</table>

<%= render :partial => 'shared/more', :locals => {:record => record} %>

<%= render :partial => 'shared/object_toolbar' , :locals => {:controller_name => backend.class.to_s.pluralize.downcase, :id => backend.id} %>

<% end %>

app/views/backends/_integrations_table.erb
<% integrations||=@integrations %>
<% table_options||={} %>

<%= redpill_table(integrations,table_options) do |table| 
  table.add_column(:name => "Integration",:order => "integration", :width =>"50%") { |o| o.integration.name}
  table.add_column(:name => "Client since",:order => "starts_at",:width =>"50%") { |o| o.starts_at}
  table.row_linker { |o| integration_url(o.integration_id) }
end %>

app/views/backends/_integrations_table.html.erb
<% integrations||=@integrations %>
<% table_options||={} %>

<%= redpill_table(integrations,table_options) do |table| 
  table.add_column(:name => :name,:order => "name", :width => "50%") { |o| link_to(o.name, subscriptions_integration_url(o)) }
  table.add_column(:name => :group,:order => "group", :width => "50%",&:group)
  table.row_linker { |o| subscriptions_integration_url(o) }
end %>

app/views/backends/_table.html.erb
<% backends||=@backends %>
<% table_options||={} %>

<%= redpill_table(backends,table_options) do |table| 
  table.add_column(:name => "name",:order => "name",:width => "30%") { |o| link_to(o.name, integrations_backend_url(o)) }
  table.add_column(:name => "group",:order => "group",:width => "30%") { |o| o.group }
  table.add_column(:name => :id,:order => "identifier", :width => "20%") {|o| o.identifier }
  table.add_column(:name => :integrations,:order => "integration_count", :width => "30%") {|o| o.integration_count }
	table.row_linker { |o| integrations_backend_url(o) }
end %>

app/views/backends/_tabs.html.erb
<div id="backends_tab" class="tab">
	<ul class="tabs">
		<%= tab_for("Integrations", integrations_backend_url(@backend)) %>
    <%= tab_for("Contacts", contacts_backend_url(@backend)) %>
    <%= tab_for("Stakeholders", {} ,{selected: false,:class => "disabled"}) %>
    <%= tab_for("Documentation", {} ,{selected: false,:class => "disabled"}) %>
    <%= tab_for("Statistics", {} ,{selected: false,:class => "disabled"}) %>
	</ul>
</div>

<div class="clr"></div>

app/views/backends/contacts.html.erb
<% roles||=@roles %>
<% pages||=PaginationHelper.pages(roles,params) %>
<% show_csv_export_button=true %>
<%= render :partial => "backend" %>

<%= render :partial => "tabs" %>
<div id="result">
		<div id="table">
      <%= render :partial => "shared/table_toolbar", :locals => {:name => "contacts", :collection => roles, :pages => pages, :show_csv_export_button => show_csv_export_button} %>
      <%= render :partial => "roles/table", :locals => {:roles => pages.current_page} %>
		</div>
</div>

app/views/backends/index.html.erb
<% backends||=@backends%>
<% pages||=PaginationHelper.pages(backends,params) %>
<% show_csv_export_button=true %>
<% content_for :window_header do %>
<%= if controller.action_name == "index"
	"backends"
	else
		controller.action_name.titleize
end %>
<% end %>

<div id="result">
  <%= render :partial => 'shared/table_toolbar', :locals => {:collection => backends, :show_csv_export_button => show_csv_export_button, :pages => pages} %>
	<div id="table">
    <%= render :partial => "table", :locals => {:backends => pages.current_page} %>	
	</div>
</div>

app/views/backends/integrations.html.erb
<% integrations||=@integrations %>
<% pages||=PaginationHelper.pages(integrations,params) %>
<% show_csv_export_button=true %>
<%= render :partial => "backend" %>

<%= render :partial => "tabs" %>
<div id="result">
		<div id="table">
      <%= render :partial => "shared/table_toolbar", :locals => {:name => "integrations", :collection => integrations, :pages => pages, :show_csv_export_button => show_csv_export_button} %>
      <%= render :partial => "integrations_table", :locals => {:integrations => pages.current_page} %>
		</div>
</div>

app/views/backends/show.html.erb
<%= render :partial => "consumer" %>

<%= render :partial => "tabs" %>