config/routes.rb
Rails.application.routes.draw do

  root 'integrations#index'

  resources :integrations, :constraints => { :id => /.*/ } do
    member do
      get 'subscriptions'
      get 'relations'
      get 'backends'
      get 'contacts'
    end
  end

  resources :clients, :constraints => { :id => /.*/ } do
    member do
      get 'subscriptions'
      get 'contacts'
    end
  end

  resources :backends, :constraints => { :id => /.*/ } do
    member do
      get 'integrations'
      get 'contacts'
    end
  end

  resources :systems, :constraints => { :id => /.*/ } do
    member do
      get 'provides'
      get 'contacts'
    end
  end

  resources :contacts, :constraints => { :id => /.*/ } do
    member do
      get 'roles'
    end
  end

end

app/models/client.rb
class Client
  include ActiveModel::Model
  attr_accessor  :identifier,:name, :group, :system_id
  attr_accessor :properties
  attr_accessor :description,:tags

  def self.all
    Registry.clients
  end

  def self.find_by_id(id)
    all.find {|s| s.id==id}
  end

  def self.find_all_by_system_id(system_id)
    all.find_all {|s| s.id==system_id}
  end

  def initialize(identifier)
    self.identifier=identifier
    @properties=[]
  end

  def system
    System.find_by_id(system_id)
  end

  def group
    @group || (system && system.group)
  end

  def subscriptions
   Subscription.find_all_by_client_id(self.id) 
  end

  def integration_count
    subscriptions.count
  end

  def contact_roles
    Role.find_all_by_client_id(self.id)
  end


  def to_s
    name || identifier
  end

  def name
    @name || (system && system.name) || identifier
  end

  def id
    self.identifier.gsub(/[^\w]/,"_") 
  end

  def persisted?
    true
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    params[:order] ||= 'name'
    keys=["name","group", "identifier","integration_count"]
    @clients = filter_and_sort(Client.all,keys,params)

    respond_to do |format|
      format.html # index.html.erb
      format.csv # index.csv.rb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find_by_id(params[:id])

    respond_to do |format|
      format.html { redirect_to subscriptions_client_url(@client) }
      format.json { render json: @client }
    end
  end

  # GET /clients/1/subscriptions
  # GET /clients/1/subscriptions.json
  def subscriptions
    params[:order] ||= 'integration'
    keys=["integration","starts_at","ends_at","debit_system"]
    @client = Client.find_by_id(params[:id])
    @subscriptions = filter_and_sort(@client.subscriptions,keys,params)

    respond_to do |format|
      format.html
      format.csv 
      format.json { render json: @subscriptions }
    end
  end

  # GET /clients/1/contacts
  # GET /clients/1/contacts.json
  def contacts
    params[:order]||='contact'
    keys=["contact","name","email"]
    @client = Client.find_by_id(params[:id])
    @roles = filter_and_sort(@client.contact_roles,keys,params)

    respond_to do |format|
      format.html 
      format.csv { render template: "shared/contacts.csv.rb"}
      format.json { render json: @roles }
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<% client||=@client %>
<% record||=client %>
<% hide_toolbar||=false %>

<%= div_for(client,:class => 'show') do %>
<table class="show" width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <th><%= "Name" %>:</th>
		<td><%= client.name %></td>
	  <th><%= "Id" %>:</th>
		<td><%= client.identifier %></td>
	</tr>
	<tr>
	  <th><%= "System" %>:</th>
    <td><%= client.system && link_to(client.system,system_path(client.system))%></td>
	  <th><%= "Group" %>:</th>
    <td><%= client.group %></td>
	</tr>
</table>

<%= render :partial => 'shared/more', :locals => {:record => record} %>

<%= render :partial => 'shared/object_toolbar' , :locals => {:controller_name => client.class.to_s.pluralize.downcase, :id => client.id} %>

<% end %>

app/views/clients/_subscriptions_table.erb
<% subscriptions||=@subscriptions %>
<% table_options||={} %>

<%= redpill_table(subscriptions,table_options) do |table| 
  table.add_column(:name => "Integration",:order => "integration", :width =>"30%") { |o| o.integration.name}
  table.add_column(:name => "Client since",:order => "starts_at",:width =>"20%") { |o| o.starts_at}
  table.add_column(:name => "Client to",:order => "ends_at",:width =>"20%") { |o| o.ends_at}
  table.add_column(:name => "Debit system",:order => "debit_system",:width =>"20%") { |o| o.debit_system}
  table.row_class { |o| o.ended? && "inactive"}
  table.row_linker { |o| integration_url(o.integration_id) }
end %>

app/views/clients/_table.html.erb
<% clients||=@clients %>
<% table_options||={} %>

<%= redpill_table(clients,table_options) do |table| 
  table.add_column(:name => "name",:order => "name",:width => "30%") { |o| link_to(o.name, subscriptions_client_url(o)) }
  table.add_column(:name => "group",:order => "group",:width => "30%") { |o| o.group }
  table.add_column(:name => :id,:order => "identifier", :width => "20%") {|o| o.identifier }
  table.add_column(:name => "Integrations",:order => "integration_count", :width => "30%") {|o| o.integration_count }
	table.row_linker { |o| subscriptions_client_url(o) }
end %>

app/views/clients/_tabs.html.erb
<div id="clients_tab" class="tab">
	<ul class="tabs">
		<%= tab_for("Integrations", subscriptions_client_url(@client)) %>
    <%= tab_for("Contacts", contacts_client_url(@client)) %>
    <%= tab_for("Documentation", {} ,{selected: false,:class => "disabled"}) %>
    <%= tab_for("Statistics", {} ,{selected: false,:class => "disabled"}) %>
	</ul>
</div>

<div class="clr"></div>

app/views/clients/contacts.html.erb
<% roles||=@roles %>
<% pages||=PaginationHelper.pages(roles,params) %>
<% show_csv_export_button=true %>
<%= render :partial => "client" %>

<%= render :partial => "tabs" %>
<div id="result">
		<div id="table">
      <%= render :partial => "shared/table_toolbar", :locals => {:name => "contacts", :collection => roles, :pages => pages, :show_csv_export_button => show_csv_export_button} %>
      <%= render :partial => "roles/table", :locals => {:roles => pages.current_page} %>
		</div>
</div>

app/views/clients/index.html.erb
<% clients||=@clients%>
<% pages||=PaginationHelper.pages(clients,params) %>
<% content_for :window_header do %>
<%= if controller.action_name == "index"
	"clients"
	else
		controller.action_name.titleize
end %>
<% end %>

<div id="result">
  <%= render :partial => 'shared/table_toolbar', :locals => {:collection => clients, :show_csv_export_button => true, :pages => pages} %>
	<div id="table">
    <%= render :partial => "table", :locals => {:clients => pages.current_page} %>	
	</div>
</div>

app/views/clients/subscriptions.html.erb
<% subscriptions||=@subscriptions %>
<% pages||=PaginationHelper.pages(subscriptions,params) %>
<% show_csv_export_button=true %>
<%= render :partial => "client" %>

<%= render :partial => "tabs" %>
<div id="result">
		<div id="table">
      <%= render :partial => "shared/table_toolbar", :locals => {:name => "integrations", :collection => subscriptions, :pages => pages, :show_csv_export_button => show_csv_export_button} %>
      <%= render :partial => "subscriptions_table", :locals => {:subscriptions => pages.current_page} %>
		</div>
</div>