config/routes.rb
Rails.application.routes.draw do

  root 'integrations#index'

  resources :integrations, :constraints => { :id => /.*/ } do
    member do
      get 'subscriptions'
      get 'relations'
      get 'backends'
      get 'contacts'
    end
  end

  resources :clients, :constraints => { :id => /.*/ } do
    member do
      get 'subscriptions'
      get 'contacts'
    end
  end

  resources :backends, :constraints => { :id => /.*/ } do
    member do
      get 'integrations'
      get 'contacts'
    end
  end

  resources :systems, :constraints => { :id => /.*/ } do
    member do
      get 'provides'
      get 'contacts'
    end
  end

  resources :contacts, :constraints => { :id => /.*/ } do
    member do
      get 'roles'
    end
  end

end

app/models/integration.rb
class Integration 
  include ActiveModel::Model
  attr_accessor :identifier, :name, :group, :system_id,:type
  attr_accessor :protocol, :format
  attr_accessor :properties
  attr_accessor :description,:tags

  def self.all
    Registry.integrations
  end

  def self.find_by_id(id)
    all.find {|s| s.id==id}
  end

  def self.find_all_by_system_id(system_id)
    all.find_all {|s| s.system_id==system_id}
  end

  def initialize(identifier)
    self.identifier=identifier
    @properties=[]
  end

  def subscriptions
   Subscription.find_all_by_integration_id(self.id) 
  end

  def client_count
   subscriptions.count
  end

  def relations
   IntegrationRelation.find_all_by_integration_id(self.id) 
  end

  def backends
   IntegrationBackend.find_all_by_integration_id(self.id).map {|s| s.backend}
  end

  def contact_roles
    Role.find_all_by_integration_id(self.id)
  end

  def system
    System.find_by_id(system_id)
  end

  def to_s
    name
  end

  def id
    self.identifier.gsub(/[^\w]/,"_") 
  end

  def persisted?
    true
  end
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController
  # GET /integrations
  # GET /integrations.json
  def index
    params[:order]||='name'
    keys=["name","group","client_count","type","protocol"]
    @integrations = filter_and_sort(Integration.all,keys,params)

    respond_to do |format|
      format.html # index.html.erb
      format.csv # index.csv.rb
      format.json { render json: @integrations }
    end
  end

  # GET /integrations/1
  # GET /integrations/1.json
  def show
    @integration=Integration.find_by_id(params[:id])

    respond_to do |format|
      format.html { redirect_to subscriptions_integration_url(@integration) }
      format.json { render json: @integration }
    end
  end

  # GET /integrations/1/subscriptions
  # GET /integrations/1/subscriptions.json
  def subscriptions
    params[:order]||='client'
    keys=["client","starts_at","ends_at","debit_system"]
    @integration=Integration.find_by_id(params[:id])
    @subscriptions = filter_and_sort(@integration.subscriptions,keys,params)

    respond_to do |format|
      format.html 
      format.csv 
      format.json { render json: @subscriptions }
    end
  end

  # GET /integrations/1/relations
  # GET /integrations/1/relations.json
  def relations
    params[:order]||='relation_type'
    keys=["relation_type","related_integration","description"]
    @integration=Integration.find_by_id(params[:id])
    @relations = filter_and_sort(@integration.relations,keys,params)

    respond_to do |format|
      format.html 
      format.csv
      format.json { render json: @relations }
    end
  end


  # GET /integrations/1/backends
  # GET /integrations/1/backends.json
  def backends
    params[:order]||='name'
    keys=["id","name","integration_count"]
    @integration=Integration.find_by_id(params[:id])
    @backends = filter_and_sort(@integration.backends,keys,params)

    respond_to do |format|
      format.html 
      format.csv 
      format.json { render json: @backends }
    end
  end

  # GET /integrations/1/contacts
  # GET /integrations/1/contacts.json
  def contacts
    @show_email_button=true
    params[:order]||='contact'
    keys=["contact","name","email"]
    @integration=Integration.find_by_id(params[:id])
    @roles = filter_and_sort(@integration.contact_roles,keys,params)

    respond_to do |format|
      format.html 
      format.csv { render template: "shared/contacts.csv.rb"}
      format.json { render json: @roles }
    end
  end


end

app/helpers/integrations_helper.rb
module IntegrationsHelper
end

app/views/integrations/_integration.html.erb
<% integration||=@integration %>
<% record||=integration %>
<% hide_toolbar||=false %>

<%= div_for(integration,:class => 'show') do %>
<table class="show" width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
	  <th><%= "Name" %>:</th>
		<td><%= integration.name %></td>
	  <th><%= "Group" %>:</th>
		<td><%= integration.group %></td>
	</tr>
	<tr>
	  <th><%= "Id" %>:</th>
		<td><%= integration.identifier %></td>
	  <th><%= "System" %>:</th>
    <td><%= integration.system && link_to(integration.system,system_path(integration.system))%></td>
	</tr>

</table>

<%= render :partial => 'shared/more', :locals => {:record => record} %>

<%= render :partial => 'shared/object_toolbar' , :locals => {:controller_name => integration.class.to_s.pluralize.downcase, :id => integration.id} %>

<% end %>

app/views/integrations/_relations_table.erb
<% relations||=@relations %>
<% table_options||={} %>

<%= redpill_table(relations,table_options) do |table| 
  table.add_column(:name => "Realtion",:order => "relation_type", :width =>"20%") { |o| o.relation_type}
  table.add_column(:name => "Integration",:order => "related_integration", :width =>"30%") { |o| o.related_integration}
  table.add_column(:name => "Description",:order => "description", :width =>"40%") { |o| o.description}
  table.row_linker { |o| integration_url(o.related_integration_id) }
end %>

app/views/integrations/_subscriptions_table.erb
<% subscriptions||=@subscriptions %>
<% table_options||={} %>

<%= redpill_table(subscriptions,table_options) do |table| 
  table.add_column(:name => "Client",:order => "client", :width =>"30%") { |o| o.client_id}
  table.add_column(:name => "Client since",:order => "starts_at", :width =>"20%") { |o| o.starts_at}
  table.add_column(:name => "Client to",:order => "ends_at", :width =>"20%") { |o| o.ends_at}
  table.add_column(:name => "Debit system",:order => "debit_system",:width =>"20%") { |o| o.debit_system}
  table.row_class { |o| o.ended? && "inactive"}
  table.row_linker { |o| client_url(o.client_id) }
end %>

app/views/integrations/_table.html.erb
<% integrations||=@integrations %>
<% table_options||={} %>

<%= redpill_table(integrations,table_options) do |table| 
  table.add_column(:name => :name,:order => "name", :width => "40%") { |o| link_to(o.name, subscriptions_integration_url(o)) }
  table.add_column(:name => :group,:order => "group", :width => "20%",&:group)
  table.add_column(:name => :type,:order => "type", :width => "20%",&:type)
  table.add_column(:name => :protocol,:order => "protocol", :width => "20%",&:protocol)
  table.add_column(:name => "Clients",:order => "client_count", :width => "20%",&:client_count)
  table.row_linker { |o| subscriptions_integration_url(o) }
end %>

app/views/integrations/_tabs.html.erb
<div id="integration_tab" class="tab">
	<ul class="tabs">
		<%= tab_for("Clients", subscriptions_integration_url(@integration)) %>
		<%= tab_for("Contacts", contacts_integration_url(@integration)) %>
		<%= tab_for("Backends", backends_integration_url(@integration)) %>
		<%= tab_for("Relations", relations_integration_url(@integration)) %>
    <%= tab_for("Stakeholders", {} ,{selected: false,:class => "disabled"}) %>
    <%= tab_for("Documetation", {} ,{selected: false,:class => "disabled"}) %>
    <%= tab_for("Statistics", {} ,{selected: false,:class => "disabled"}) %>
		<%# tab_for("Issues",  {} ,{selected: false,:class => "disabled"}) %>
	</ul>
</div>

<div class="clr"></div>

app/views/integrations/backends.html.erb
<% backends||=@backends %>
<% pages||=PaginationHelper.pages(backends,params) %>
<% show_csv_export_button=true %>
<%= render :partial => "integration" %>

<%= render :partial => "tabs" %>
<div id="result">
  <%= render :partial => "shared/table_toolbar", :locals => {:name => "backends", :collection => backends, :pages => pages, :show_csv_export_button => show_csv_export_button} %>
  <div id="table">
    <%= render :partial => "backends/table", :locals => {:backends => pages.current_page} %>
  </div>
</div>

app/views/integrations/contacts.html.erb
<% roles||=@roles %>
<% pages||=PaginationHelper.pages(roles,params) %>
<% show_csv_export_button=true %>
<%= render :partial => "integration" %>

<%= render :partial => "tabs" %>
<div id="result">
  <%= render :partial => "shared/table_toolbar", :locals => {:name => "contacts", :collection => roles, :pages => pages, :show_csv_export_button => show_csv_export_button} %>
		<div id="table">
      <%= render :partial => "roles/table", :locals => {:roles => pages.current_page} %>
		</div>
</div>

app/views/integrations/index.html.erb
<% integrations||=@integrations %>
<% pages||=PaginationHelper.pages(integrations,params) %>
<% show_csv_export_button=true %> 
<% content_for :window_header do %>
<%= if controller.action_name == "index"
	"Integrations"
	else
		controller.action_name.titleize
end %>
<% end %>

<div id="result">
  <%= render :partial => 'shared/table_toolbar', :locals => {:collection => integrations, :show_csv_export_button => show_csv_export_button, :pages => pages} %>
	<div id="table">
    <%= render :partial => "table", :locals => {:integrations => pages.current_page} %>	
	</div>
</div>

app/views/integrations/relations.html.erb
<% relations||=@relations %>
<% pages||=PaginationHelper.pages(relations,params) %>
<% show_csv_export_button=true %>
<%= render :partial => "integration" %>

<%= render :partial => "tabs" %>
<div id="result">
		<div id="table">
      <%= render :partial => "shared/table_toolbar", :locals => {:name => "relations", :collection => relations, :pages => pages, :show_csv_export_button => show_csv_export_button} %>
      <%= render :partial => "relations_table", :locals => {:relations => pages.current_page} %>
		</div>
</div>

app/views/integrations/subscriptions.html.erb
<% subscriptions||=@subscriptions %>
<% pages||=PaginationHelper.pages(subscriptions,params) %>
<% show_csv_export_button=true %>
<%= render :partial => "integration" %>

<%= render :partial => "tabs" %>
<div id="result">
		<div id="table">
      <%= render :partial => "shared/table_toolbar", :locals => {:name => "clients", :collection => subscriptions, :pages => pages, :show_csv_export_button => show_csv_export_button} %>
      <%= render :partial => "subscriptions_table", :locals => {:subscriptions => pages.current_page} %>
		</div>
</div>