config/routes.rb
Rails.application.routes.draw do

  root 'integrations#index'

  resources :integrations, :constraints => { :id => /.*/ } do
    member do
      get 'subscriptions'
      get 'relations'
      get 'backends'
      get 'contacts'
    end
  end

  resources :clients, :constraints => { :id => /.*/ } do
    member do
      get 'subscriptions'
      get 'contacts'
    end
  end

  resources :backends, :constraints => { :id => /.*/ } do
    member do
      get 'integrations'
      get 'contacts'
    end
  end

  resources :systems, :constraints => { :id => /.*/ } do
    member do
      get 'provides'
      get 'contacts'
    end
  end

  resources :contacts, :constraints => { :id => /.*/ } do
    member do
      get 'roles'
    end
  end

end

app/views/layouts/_notice.html.erb
<div id="flash" style="<%= "display:none;" unless flash[:notice]  %>" >
	<%= flash[:notice] %>
</div>

app/views/layouts/_search.html.erb
<div id="search">
	<div id="search_form">
		<form name="search_form" action="/search" method="get" style="display:inline;" >
			<%= text_field_tag("query", params[:query], :placeholder => "Search", 
																								
																									:accesskey => 'F', 
                                                  :disabled=> true) %>
		</form>
	</div>
</div>

app/views/layouts/_sidebar.html.erb
<%= redpill_sidebar do |sidebar|  %>
  <%= sidebar.item("Integrations",integrations_path)%>
  <%= sidebar.item("Clients",clients_path) %>
  <%= sidebar.item("Backends",backends_path ) %>
  <%= sidebar.item("Systems",systems_path ) %>
  <%= sidebar.item("Contacts",contacts_path ) %>
<% end %>

app/views/layouts/_window_header.html.erb
<% if controller.action_name == 'show' && respond_to?(:current_resource)  %>
	<%= current_resource %>
<% else %>
	<%= controller.controller_name.titleize %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EsbInventory</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<body>
  <div id="wrapper">
  	<noscript>
  		<div id="noscript">
  			<%= "[This web application requires javascript.]" %>
  		</div>
  	</noscript>
  	<div id="right-wrap">
  		<div id="right">
			<%# <div id="info-logotype"></div> %>
				<div id="notice">
				<%= render :partial => 'layouts/notice' %>
				</div>
			<div id="window">
				<div class="bottomRightCorner"><div class="bottomLeftCorner"><div class="topRightCorner"><div class="topLeftCorner">
		  			<div id="content_box">
							<div id="window-header">
								<h3><%= render(:partial => 'layouts/window_header') %></h3>
							</div>	
		  				<%= yield %>
		  			</div>
		  		</div></div></div></div>
		  	</div>
  		</div>
  	</div>

  	<div id="left">
			<a href="/license.html" target="blank">
				<div id="logotype"></div>
			</a>


			<%= render :partial => 'layouts/sidebar' %>
						
  	</div>

  </div>

	<%# IE6 min-width hack %>
	 <script type="text/javascript">
	//<![CDATA[
	 if (document.body.clientWidth < 980)
	 {
	 document.body.style.width = 980;
	 }
	//]]>
	</script>


</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
	<%= stylesheet_link_tag 'login' %>
	
	
	<title><%= "ESB Inventory" %></title>
</head>
<body>
<div id="application">
	<% if flash[:notice]%>
	<div id="notice"><%= flash[:notice] %></div>
	<% end %>
<%= yield %>
</div>
</body>
</html>